# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ba7aa7d7702d19a508e614962c5b539962a0859bc56dd28ffa369b720183e6007becd80fe14b873e4616a7eed0a542cdfa0583d961cd4fd99512ba7a7bde953

test:
  secret_key_base: 64248e8149d3b6f6cf8b1eef8201e0cc716e6cc29e1f574e52f6e2338d16282c24a16af02f63ce88397e9f2ff2a7061be3530647ad569a48d7ccb05e3cd95d3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
